### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './dataset/corpus.pkl'

### ISSUE THREAD

**Issue by huanghonggit** [vic85821/sentence_classification_nlp#1]
Hello, I just learned elmo bert wants to debug your code. When I follow README.md   run python preprocess.py ./dataset  get this  error.  Can you give me advice？or Can you give me the complete code project, thank you very much

Traceback (most recent call last):
  File "preprocess.py", line 240, in <module>
    main(args)
  File "preprocess.py", line 217, in main
    preprocess.load_processed_files()
  File "preprocess.py", line 111, in load_processed_files
    with open(corpus_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './dataset/corpus.pkl'

**Comment by vic85821** [comment]
Sorry for the late reply. I have updated the repo with the needed files. 
If you have any question, feel free to contact me. 

Thanks.

**Comment by huanghonggit** [comment]
Thank you very much!




------------------ 原始邮件 ------------------
发件人: "YU-CHENG CHANG"<notifications@github.com>; 
发送时间: 2019年6月28日(星期五) 晚上8:23
收件人: "vic85821/sentence_classification_nlp"<sentence_classification_nlp@noreply.github.com>; 
抄送: "咕噜咕噜"<1213949528@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [vic85821/sentence_classification_nlp] FileNotFoundError: [Errno2] No such file or directory: './dataset/corpus.pkl' (#1)




Sorry for the late reply. I have updated the repo with the needed files.
 If you have any question, feel free to contact me.
 
Thanks.

**Comment by huanghonggit** [comment]
Thank you very much!



------------------ 原始邮件 ------------------
发件人: "YU-CHENG CHANG"<notifications@github.com>; 
发送时间: 2019年6月28日(星期五) 晚上8:23
收件人: "vic85821/sentence_classificatio"<sentence_classification_nlp@noreply.github.com>; 
抄送: "咕噜咕噜"<1213949528@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [vic85821/sentence_classification_nlp] FileNotFoundError: [Errno2] No such file or directory: './dataset/corpus.pkl' (#1)




Sorry for the late reply. I have updated the repo with the needed files.
 If you have any question, feel free to contact me.
 
Thanks.
